"""`aspose_words_mcp`'s own package namespace.

Re-exports every tool function and object-kind response TypedDict at the top-level package
namespace, since `generate_server_module_source`'s own rendered server imports them via
`from aspose_words_mcp import (...)` rather than reaching into `aspose_words_mcp.tools` directly.

Auto-generated by Codegen (FR4) from the tracked IR — do not edit by hand.
Regenerate via `run_lifecycle.py --product <product> --action rebuild` instead of patching this file directly (rubric gate 8: hand-patched generated output is a hard-gate failure).
"""

from __future__ import annotations

from aspose_words_mcp import tools
from aspose_words_mcp.tools import (
    GetCommentsResponse,
    GetDocumentBookmarksResponse,
    GetDocumentPropertiesResponse,
    GetDocumentStatisticsResponse,
    PostCompareDocumentResponse,
    PostDocumentSaveAsResponse,
    PostReplaceTextResponse,
    PutCreateDocumentResponse,
    words_compare_document,
    words_convert_to_format,
    words_create_document,
    words_download_document,
    words_get_comments,
    words_get_document_bookmarks,
    words_get_document_properties,
    words_get_document_statistics,
    words_replace_text,
    words_save_document_as,
)


TOOL_ANNOTATIONS: dict[str, dict[str, object]] = {
    "words_compare_document": {
        "title": 'Compare a Cloud-stored Word document against another and produce a tracked-changes result',
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "words_convert_to_format": {
        "title": 'Convert a local Word document to another format',
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_create_document": {
        "title": 'Create a new, blank Word document in Aspose Cloud Storage',
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "words_download_document": {
        "title": 'Download an existing Cloud-stored Word document in a given format',
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_get_comments": {
        "title": 'Get comments from a Word document',
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_get_document_bookmarks": {
        "title": "Get a Word document's bookmarks",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_get_document_properties": {
        "title": "Get a Word document's built-in and custom properties",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_get_document_statistics": {
        "title": "Get a Word document's statistics (word/page/paragraph counts, etc.)",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_replace_text": {
        "title": 'Replace text within a Cloud-stored Word document',
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "words_save_document_as": {
        "title": 'Save a Cloud-stored Word document in another format via explicit save options',
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
}

__all__ = [
    "tools",
    "GetCommentsResponse",
    "GetDocumentBookmarksResponse",
    "GetDocumentPropertiesResponse",
    "GetDocumentStatisticsResponse",
    "PostCompareDocumentResponse",
    "PostDocumentSaveAsResponse",
    "PostReplaceTextResponse",
    "PutCreateDocumentResponse",
    "words_compare_document",
    "words_convert_to_format",
    "words_create_document",
    "words_download_document",
    "words_get_comments",
    "words_get_document_bookmarks",
    "words_get_document_properties",
    "words_get_document_statistics",
    "words_replace_text",
    "words_save_document_as",
    "TOOL_ANNOTATIONS",
]
