"""`aspose-words-mcp` — Words' curated 9-tool MCP surface (Sprint 11, PRD Section 2.6/FR15b; 3 more
added Sprint 13, FR4 body-param support).

A genuinely separate, installable, versioned package (zero import dependency on the builder's own
`mcp_builder` — same Requirement 5.1 discipline `aspose-storage-core-mcp` established in Sprint 7,
extended here to every per-product package) containing Words' 6 curated tools as plain, undecorated
functions. Unlike `aspose-storage-core-mcp`, this package has no core/extra split (execution plan
Fork 4) — it is not a shared dependency of any other product, so every curated tool lives here.

Declares a real, ordinary versioned dependency on `aspose-storage-core-mcp` (`pyproject.toml`) for
the bundled core subset (`storage_upload_file`/`storage_download_file`/`storage_list_files`/
`storage_delete_file`, FR15b) — a user connected to only this server can still upload a file, convert
it, and download the result, with no second server connection (this sprint's own exit criterion).
`generated/words/server.py` is where that bundling actually happens; this package only owns Words'
own tools.

`words_split_document` was part of this package's original 7-tool curated set but is deferred
(Sprint 11 real API migration): its real v4.0 endpoint could not be found live (its v1.1 relative
path and several guessed variants all 404) and was not guessed further blindly — see the Sprint 11
execution plan's carry-forward items.

Regenerated by the builder's Codegen agent (`mcp_builder.codegen`) from the tracked, curated-subset
Words IR — never hand-patched (rubric gate 8).
"""

from __future__ import annotations

from aspose_words_mcp import tools
from aspose_words_mcp.tools import (
    GetDocumentBookmarksResponse,
    GetDocumentPropertiesResponse,
    GetDocumentStatisticsResponse,
    PostCompareDocumentResponse,
    PostDocumentSaveAsResponse,
    PostReplaceTextResponse,
    PutCreateDocumentResponse,
    words_compare_document,
    words_convert_to_format,
    words_create_document,
    words_download_document,
    words_get_document_bookmarks,
    words_get_document_properties,
    words_get_document_statistics,
    words_replace_text,
    words_save_document_as,
)

TOOL_ANNOTATIONS: dict[str, dict[str, object]] = {
    "words_convert_to_format": {
        "title": "Convert a local Word document to another format",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_download_document": {
        "title": "Download an existing Cloud-stored Word document in a given format",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_create_document": {
        "title": "Create a new, blank Word document in Aspose Cloud Storage",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "words_get_document_properties": {
        "title": "Get a Word document's built-in and custom properties",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_get_document_statistics": {
        "title": "Get a Word document's statistics (word/page/paragraph counts, etc.)",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_get_document_bookmarks": {
        "title": "Get a Word document's bookmarks",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "words_replace_text": {
        "title": "Replace text within a Cloud-stored Word document",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "words_compare_document": {
        "title": "Compare a Cloud-stored Word document against another and produce a tracked-changes result",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "words_save_document_as": {
        "title": "Save a Cloud-stored Word document in another format via explicit save options",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
}

__all__ = [
    "tools",
    "words_convert_to_format",
    "words_download_document",
    "words_create_document",
    "words_get_document_properties",
    "words_get_document_statistics",
    "words_get_document_bookmarks",
    "words_replace_text",
    "words_compare_document",
    "words_save_document_as",
    "GetDocumentBookmarksResponse",
    "GetDocumentPropertiesResponse",
    "GetDocumentStatisticsResponse",
    "PutCreateDocumentResponse",
    "PostReplaceTextResponse",
    "PostCompareDocumentResponse",
    "PostDocumentSaveAsResponse",
    "TOOL_ANNOTATIONS",
]
