"""`aspose-words-mcp`'s own standalone, runnable MCP server.

Auto-generated by Codegen's `generate_server_module_source` from the tracked IR — regenerate via
`run_lifecycle.py --product words --action rebuild` instead of patching this file directly
(rubric gate 8: hand-patched generated output is a hard-gate failure, same discipline this
package's own `tools.py` header states).

This is the real runnable entry point the public `aspose-words-mcp` package ships. Before
this file existed, the only actual MCP server for this product lived inside the private builder
repo's own staging area (its `generated/words/server.py`), which imports the builder's own
internal auth client, tool-spec builder, IR document schema, lessons store, and semantic-db
modules directly, and loaded a live `ir/words/*.json` snapshot at import time just to
recompute each tool's annotations and structured-output flag. None of that exists once this
package is the only thing actually published (Decision 6: every "published" release so far has
only ever been a GitLab tag of the *tools library*, `tools.py` — never a runnable server) — so
this file is a deliberate, self-contained rendering with **zero import dependency on the private
builder package**, mirroring every other file in this package's own zero-import-dependency-on-
the-builder discipline (see this package's own `_auth.py`/`_path_resolution.py` docstrings).
Every tool's annotations and
`structured_output` flag are baked into this file as literal values at the time it was
generated — never recomputed from a live IR file at server startup, since no IR file ships with
this package.

Bundles Storage's core-4 tools (FR15b) exactly like the existing staging-area servers do, so a
user connected to only this server can upload a file, operate on it, and download the result
with no second server connection.
"""

from __future__ import annotations

from typing import Any

from aspose_storage_core_mcp import (
    DeleteFileResponse,
    storage_delete_file,
    storage_download_file,
    storage_list_files,
    storage_upload_file,
)
from aspose_words_mcp import (
    GetAvailableFontsResponse,
    GetCommentsResponse,
    GetDocumentBookmarksResponse,
    GetDocumentPropertiesResponse,
    GetDocumentStatisticsResponse,
    PostCompareDocumentResponse,
    PostDocumentSaveAsResponse,
    PostReplaceTextResponse,
    PutCreateDocumentResponse,
    ResetCacheResponse,
    words_compare_document,
    words_convert_to_format,
    words_create_document,
    words_download_document,
    words_get_available_fonts,
    words_get_comments,
    words_get_document_bookmarks,
    words_get_document_properties,
    words_get_document_statistics,
    words_replace_text,
    words_reset_cache,
    words_save_document_as,
)
from aspose_words_mcp._auth import AsposeAuthClient
from mcp.server.mcpserver import MCPServer
from mcp_types import ToolAnnotations


server = MCPServer(
    "aspose-words",
    version="0.1.0",
    instructions="Real Codegen-generated MCP tools for Words' curated operation set, plus Storage's bundled core subset (upload/download/list/delete).",
)


_auth: AsposeAuthClient | None = None


def _get_auth() -> AsposeAuthClient:
    global _auth
    if _auth is None:
        _auth = AsposeAuthClient()
    return _auth


# --- Bundled Storage core subset (FR15b) ----------------------------------------------------


def storage_upload_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, content_base64: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    # Sprint 11 real bug fix: `storage_upload_file`/`storage_delete_file` gained a `base_url`
    # parameter (Slides' v3.0 finding) inserted *before* `dry_run` in their real signatures -- a
    # positional call here would have silently passed `dry_run`'s value into `base_url` instead
    # (a real, confirmed bug, never actually exercised until now). Every storage-core call below is
    # keyword-only from this point on, immune to any future parameter reordering.
    return storage_upload_file(_get_auth(), "words", filename, version_id=version_id, storage_name=storage_name, content_base64=content_base64, dry_run=dry_run)


def storage_download_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return storage_download_file(_get_auth(), "words", filename, version_id=version_id, storage_name=storage_name, output_filename=output_filename, return_base64=return_base64)


def storage_list_files_tool(folder_name: str | None = None, storage_name: str | None = None) -> dict[str, Any]:
    return storage_list_files(_get_auth(), "words", folder_name=folder_name, storage_name=storage_name)


def storage_delete_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> DeleteFileResponse:
    return storage_delete_file(_get_auth(), "words", filename, version_id=version_id, storage_name=storage_name, dry_run=dry_run)


_STORAGE_ANNOTATIONS = {
    "storage_upload_file": {"title": "Upload a file to Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False},
    "storage_download_file": {"title": "Download a file from Aspose Cloud Storage", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_list_files": {"title": "List files in an Aspose Cloud Storage folder", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_delete_file": {"title": "Delete a file from Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True},
}


_STORAGE_WRAPPERS = {
    "storage_upload_file": storage_upload_file_tool,
    "storage_download_file": storage_download_file_tool,
    "storage_list_files": storage_list_files_tool,
    "storage_delete_file": storage_delete_file_tool,
}

_STORAGE_REAL_FUNCS = {
    "storage_upload_file": storage_upload_file,
    "storage_download_file": storage_download_file,
    "storage_list_files": storage_list_files,
    "storage_delete_file": storage_delete_file,
}


# --- Words' own curated tools ------------------------------------------------------------


def words_get_document_bookmarks_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentBookmarksResponse:
    return words_get_document_bookmarks(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


def words_get_comments_tool(name: str, folder: str | None = None, storage: str | None = None, load_encoding: str | None = None) -> GetCommentsResponse:
    return words_get_comments(_get_auth(), name=name, folder=folder, storage=storage, load_encoding=load_encoding)


def words_compare_document_tool(filename: str, compare_request: dict[str, Any], folder_name: str | None = None, storage_name: str | None = None, load_encoding: str | None = None, destination_filename: str | None = None, dry_run: bool = False) -> PostCompareDocumentResponse:
    return words_compare_document(_get_auth(), filename=filename, compare_request=compare_request, folder_name=folder_name, storage_name=storage_name, load_encoding=load_encoding, destination_filename=destination_filename, dry_run=dry_run)


def words_download_document_tool(filename: str, target_format: str, folder_name: str | None = None, storage_name: str | None = None, output_path: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return words_download_document(_get_auth(), filename=filename, target_format=target_format, folder_name=folder_name, storage_name=storage_name, output_path=output_path, output_filename=output_filename, return_base64=return_base64)


def words_convert_to_format_tool(document_filename: str, target_format: str, storage_name: str | None = None, output_path: str | None = None, source_filename_hint: str | None = None, content_base64: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return words_convert_to_format(_get_auth(), document_filename=document_filename, target_format=target_format, storage_name=storage_name, output_path=output_path, source_filename_hint=source_filename_hint, content_base64=content_base64, output_filename=output_filename, return_base64=return_base64)


def words_save_document_as_tool(filename: str, save_options: dict[str, Any], folder_name: str | None = None, storage_name: str | None = None, load_encoding: str | None = None, destination_filename: str | None = None, fonts_location: str | None = None, dry_run: bool = False) -> PostDocumentSaveAsResponse:
    return words_save_document_as(_get_auth(), filename=filename, save_options=save_options, folder_name=folder_name, storage_name=storage_name, load_encoding=load_encoding, destination_filename=destination_filename, fonts_location=fonts_location, dry_run=dry_run)


def words_get_document_properties_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentPropertiesResponse:
    return words_get_document_properties(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


def words_get_available_fonts_tool(fonts_location: str | None = None) -> GetAvailableFontsResponse:
    return words_get_available_fonts(_get_auth(), fonts_location=fonts_location)


def words_reset_cache_tool(dry_run: bool = False) -> ResetCacheResponse:
    return words_reset_cache(_get_auth(), dry_run=dry_run)


def words_get_document_statistics_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None, include_comments: bool | None = None, include_footnotes: bool | None = None, include_text_in_shapes: bool | None = None) -> GetDocumentStatisticsResponse:
    return words_get_document_statistics(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name, include_comments=include_comments, include_footnotes=include_footnotes, include_text_in_shapes=include_text_in_shapes)


def words_replace_text_tool(filename: str, replace_request: dict[str, Any], folder_name: str | None = None, storage_name: str | None = None, load_encoding: str | None = None, destination_filename: str | None = None, revision_author: str | None = None, revision_date_time: str | None = None, dry_run: bool = False) -> PostReplaceTextResponse:
    return words_replace_text(_get_auth(), filename=filename, replace_request=replace_request, folder_name=folder_name, storage_name=storage_name, load_encoding=load_encoding, destination_filename=destination_filename, revision_author=revision_author, revision_date_time=revision_date_time, dry_run=dry_run)


def words_create_document_tool(storage_name: str | None = None, filename: str | None = None, folder_name: str | None = None, dry_run: bool = False) -> PutCreateDocumentResponse:
    return words_create_document(_get_auth(), storage_name=storage_name, filename=filename, folder_name=folder_name, dry_run=dry_run)


_PRODUCT_ANNOTATIONS = {
    "words_get_document_bookmarks": {"title": "Get a Word document's bookmarks", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_get_comments": {"title": 'Get comments from a Word document', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_compare_document": {"title": 'Compare a Cloud-stored Word document against another and produce a tracked-changes result', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "words_download_document": {"title": 'Download an existing Cloud-stored Word document in a given format', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_convert_to_format": {"title": 'Convert a local Word document to another format', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_save_document_as": {"title": 'Save a Cloud-stored Word document in another format via explicit save options', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "words_get_document_properties": {"title": "Get a Word document's built-in and custom properties", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_get_available_fonts": {"title": 'Get list of available fonts for Word processing', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_reset_cache": {"title": 'Reset font cache', "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_get_document_statistics": {"title": "Get a Word document's statistics (word/page/paragraph counts, etc.)", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "words_replace_text": {"title": 'Replace text within a Cloud-stored Word document', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "words_create_document": {"title": 'Create a new, blank Word document in Aspose Cloud Storage', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
}


_PRODUCT_WRAPPERS = {
    "words_get_document_bookmarks": words_get_document_bookmarks_tool,
    "words_get_comments": words_get_comments_tool,
    "words_compare_document": words_compare_document_tool,
    "words_download_document": words_download_document_tool,
    "words_convert_to_format": words_convert_to_format_tool,
    "words_save_document_as": words_save_document_as_tool,
    "words_get_document_properties": words_get_document_properties_tool,
    "words_get_available_fonts": words_get_available_fonts_tool,
    "words_reset_cache": words_reset_cache_tool,
    "words_get_document_statistics": words_get_document_statistics_tool,
    "words_replace_text": words_replace_text_tool,
    "words_create_document": words_create_document_tool,
}


_PRODUCT_REAL_FUNCS = {
    "words_get_document_bookmarks": words_get_document_bookmarks,
    "words_get_comments": words_get_comments,
    "words_compare_document": words_compare_document,
    "words_download_document": words_download_document,
    "words_convert_to_format": words_convert_to_format,
    "words_save_document_as": words_save_document_as,
    "words_get_document_properties": words_get_document_properties,
    "words_get_available_fonts": words_get_available_fonts,
    "words_reset_cache": words_reset_cache,
    "words_get_document_statistics": words_get_document_statistics,
    "words_replace_text": words_replace_text,
    "words_create_document": words_create_document,
}


def _register_all_tools() -> None:
    # Storage core subset first (FR15b) — same 4 tools, same annotations, every rendered
    # server bundles.
    for name, wrapper in _STORAGE_WRAPPERS.items():
        annotations = _STORAGE_ANNOTATIONS[name]
        real_description = _STORAGE_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=True,
            ),
            structured_output=True,
        )

    # Words' own curated tools.
    for name, wrapper in _PRODUCT_WRAPPERS.items():
        annotations = _PRODUCT_ANNOTATIONS[name]
        real_description = _PRODUCT_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=annotations["open_world_hint"],
            ),
            structured_output=annotations["structured_output"],
        )


_register_all_tools()


def main() -> None:
    server.run(transport="stdio")


if __name__ == "__main__":
    main()
