"""Auto-generated by Codegen (FR4) from the tracked IR — do not edit by hand.

Regenerate via `run_lifecycle.py --product words --action rebuild` instead of patching this file directly (rubric gate 8: hand-patched generated output is a hard-gate failure).
"""

from __future__ import annotations

from typing import Any, TypedDict

import requests

from aspose_words_mcp._auth import AsposeAuthClient
from aspose_words_mcp._path_resolution import resolve_local_path
from aspose_words_mcp._errors import ToolError, call_with_taxonomy

BASE_URL = "https://api.aspose.cloud/v4.0"


class GetDocumentBookmarksResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    Bookmarks: dict | None


class PostCompareDocumentResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    Document: dict | None


class PostDocumentSaveAsResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    SaveResult: dict | None


class GetDocumentPropertiesResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    DocumentProperties: dict | None


class GetDocumentStatisticsResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    DocumentLink: dict | None
    StatData: dict | None


class PostReplaceTextResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    DocumentLink: dict | None
    Matches: int | None


class PutCreateDocumentResponse(TypedDict, total=False):
    Code: int | None
    Status: str | None
    Document: dict | None


def words_get_document_bookmarks(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentBookmarksResponse:
    'Retrieves the list of bookmark information from a specified Word document stored in Aspose Cloud.\n\n- **name** – required string; the document file name, supplied as the `{name}` path segment.  \n- **folder** – optional string; query parameter indicating the folder path in the chosen storage where the document resides.  \n- **storage** – optional string; query parameter naming the storage service to be used for the document.  \n- **loadEncoding** – optional string; query parameter specifying the character encoding to apply when loading an HTML or TXT document that does not declare its own encoding.  \n- **password** – optional string; query parameter containing the password needed to open an encrypted document.\n\nThe tool returns a JSON object whose `Bookmarks` field is an array of bookmark objects, each providing the common information for a bookmark (such as its name, text, and position) extracted from the document.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/words/{filename}/bookmarks"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def words_compare_document(auth: AsposeAuthClient, filename: str, compare_request: dict[str, Any], folder_name: str | None = None, storage_name: str | None = None, load_encoding: str | None = None, destination_filename: str | None = None, dry_run: bool = False) -> PostCompareDocumentResponse:
    'This tool compares a source Word document stored in Aspose Cloud with another document and produces a new document that highlights all differences.  \n\n- **name** – string, required, path parameter: filename (including extension) of the original document to be compared.  \n- **compareData** – object, required, body parameter: must contain the following keys  \n  • **ComparingWithDocument** – string, required: filename (including extension) of the document to compare against the original.  \n  • **Author** – string, optional: name of the author to attribute the changes to.  \n  • **DateTime** – string, optional: revision date‑time in ISO‑8601 format (e.g., “2023-01-15T14:30:00Z”).  \n- **folder** – string, optional, query parameter: path of the folder in the chosen storage where the original document resides.  \n- **storage** – string, optional, query parameter: identifier of the storage service to use.  \n- **loadEncoding** – string, optional, query parameter: character encoding name (e.g., “utf-8”) to use when loading an HTML or TXT document that lacks an explicit encoding.  \n- **password** – string, optional, query parameter: password for opening an encrypted original document.  \n- **destFileName** – string, optional, query parameter: filename (including extension) for the resulting compared document; if omitted the source document is overwritten with the comparison result.  \n\nThe tool returns a JSON object with fields: status:string, code:integer, message:string\u202f(optional), and documentLink:object\u202fcontaining href:string, rel:string, and type:string.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name, "loadEncoding": load_encoding, "destFileName": destination_filename}.items() if v is not None}
    url = f"/words/{filename}/compareDocument"
    if dry_run:
        return {"dry_run": True, "operation": "PostCompareDocument"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        json=compare_request,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def words_download_document(auth: AsposeAuthClient, filename: str, target_format: str, folder_name: str | None = None, storage_name: str | None = None, output_path: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    'The tool retrieves a stored Word document, converts it to the requested format, and returns the resulting file content.\n\n- **name**: path‑parameter, string, required – exact filename of the source document (including extension).\n- **format**: query‑parameter, string, required – name of the target export format; must be a format supported by Aspose.Words (e.g., “pdf”, “docx”, “html”, “txt”, “png”, etc.).\n- **folder**: query‑parameter, string, optional – path to the folder in the storage where the source document resides; if omitted the root folder is assumed.\n- **storage**: query‑parameter, string, optional – identifier of the storage service to use; if omitted the default storage is used.\n- **loadEncoding**: query‑parameter, string, optional – character encoding to apply when loading an HTML or TXT source document that lacks an explicit encoding declaration.\n- **password**: query‑parameter, string, optional – password required to open an encrypted source document.\n- **outPath**: query‑parameter, string, optional – full storage path where the converted file should be saved; if omitted the result is returned directly in the response.\n- **fontsLocation**: query‑parameter, string, optional – folder path in the storage that contains custom fonts needed for rendering the document.\n\nThe output is a binary stream of the converted document (returned as a base64‑encoded string in the response body), accompanied by standard HTTP metadata such as content‑type indicating the chosen format.'
    params = {k: v for k, v in {"format": target_format, "folder": folder_name, "storage": storage_name, "outPath": output_path}.items() if v is not None}
    url = f"/words/{filename}"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if return_base64:
        import base64 as _base64
        return {"content_base64": _base64.b64encode(response.content).decode("ascii")}
    local_path = resolve_local_path(output_filename or filename, is_output=True)
    local_path.write_bytes(response.content)
    return {"Status": "OK", "local_path": str(local_path)}


def words_convert_to_format(auth: AsposeAuthClient, document_filename: str, target_format: str, storage_name: str | None = None, output_path: str | None = None, source_filename_hint: str | None = None, content_base64: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    'This tool uploads a document and converts it to the format you specify, optionally saving the result to a storage location you provide.  \n\n- document (formData, file, required): the source file to be converted.  \n- format (query, string, required): target format identifier (e.g., “pdf”, “docx”, “html”); must be one of the formats supported by Aspose.Words.  \n- storage (query, string, optional): name of the file storage to use for the operation.  \n- outPath (query, string, optional): full path in the selected storage where the converted file should be written.  \n- documentFileName (query, string, optional): file name to substitute for the placeholder\u202f{filename} in dynamic fields; if omitted the original source file name is used.  \n- fontsLocation (query, string, optional): path to a folder in the storage that contains custom fonts required for conversion.  \n\nThe tool returns the converted document in the requested format as a binary stream (or a confirmation response if outPath is used to store the file).'
    params = {k: v for k, v in {"format": target_format, "storage": storage_name, "outPath": output_path, "documentFileName": source_filename_hint}.items() if v is not None}
    url = "/words/convert"
    if content_base64 is not None:
        import base64 as _base64
        content = _base64.b64decode(content_base64)
    else:
        local_path = resolve_local_path(document_filename)
        content = local_path.read_bytes()
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header(), "Content-Type": "application/octet-stream"},
        data=content,
        timeout=30.0,
    ))
    if return_base64:
        import base64 as _base64
        return {"content_base64": _base64.b64encode(response.content).decode("ascii")}
    local_path = resolve_local_path(output_filename or "converted_output", is_output=True)
    local_path.write_bytes(response.content)
    return {"Status": "OK", "local_path": str(local_path)}


def words_save_document_as(auth: AsposeAuthClient, filename: str, save_options: dict[str, Any], folder_name: str | None = None, storage_name: str | None = None, load_encoding: str | None = None, destination_filename: str | None = None, fonts_location: str | None = None, dry_run: bool = False) -> PostDocumentSaveAsResponse:
    'NEEDS_HUMAN_REVIEW: Converts a Word document stored in Aspose Cloud storage to a specified format using detailed save options and saves the resulting file to the chosen storage location.  \n\n- **name** – required, path‑parameter, string: name of the source document.  \n- **saveOptionsData** – required, body‑parameter, object containing the following optional keys:  \n\u202f\u202f• **ColorMode** – string.  \n\u202f\u202f• **SaveFormat** – string (e.g., “pdf”, “docx”, “html”, etc.).  \n\u202f\u202f• **FileName** – string.  \n\u202f\u202f• **DmlRenderingMode** – string.  \n\u202f\u202f• **DmlEffectsRenderingMode** – string.  \n\u202f\u202f• **ZipOutput** – boolean.  \n\u202f\u202f• **UpdateLastSavedTimeProperty** – boolean.  \n\u202f\u202f• **UpdateSdtContent** – boolean.  \n\u202f\u202f• **UpdateFields** – boolean.  \n- **folder** – optional, query‑parameter, string: folder path where the source document resides.  \n- **storage** – optional, query‑parameter, string: name of the storage to use.  \n- **loadEncoding** – optional, query‑parameter, string: character encoding to apply when loading an HTML or TXT document without an explicit encoding.  \n- **password** – optional, query‑parameter, string: password for opening an encrypted document.  \n- **destFileName** – optional, query‑parameter, string: desired name for the saved document; if omitted the source document is overwritten.  \n- **fontsLocation** – optional, query‑parameter, string: folder in the storage that contains custom fonts.  \n\nReturns a JSON object with the top‑level fields: **savedPath** (string) – full path of the saved file in storage; **status** (string) – operation result such as “OK”; and **errorMessage** (string, optional) – description of any error that occurred.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name, "loadEncoding": load_encoding, "destFileName": destination_filename, "fontsLocation": fonts_location}.items() if v is not None}
    url = f"/words/{filename}/saveAs"
    if dry_run:
        return {"dry_run": True, "operation": "PostDocumentSaveAs"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        json=save_options,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def words_get_document_properties(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentPropertiesResponse:
    'The tool retrieves all document properties of a specified Word file stored in Aspose Cloud.  \nname (required, string, path) – the document’s filename, including its extension.  \nfolder (optional, string, query) – the path to the folder that contains the document; if omitted the root folder is assumed.  \nstorage (optional, string, query) – the identifier of the storage service to use; must match a configured storage name.  \nloadEncoding (optional, string, query) – the character encoding to apply when loading an HTML or TXT document that does not declare its own encoding.  \npassword (optional, string, query) – the password required to open the document if it is encrypted.  \nThe output is a JSON object listing each property with its name, value, and a flag indicating whether it is a built‑in property.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/words/{filename}/documentProperties"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def words_get_document_statistics(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None, include_comments: bool | None = None, include_footnotes: bool | None = None, include_text_in_shapes: bool | None = None) -> GetDocumentStatisticsResponse:
    'The tool fetches statistical information (word count, page count, character count, etc.) for a specified Word document stored in Aspose Cloud.  \n\n- **name** – required, path parameter, string: exact filename of the document, including its extension.  \n- **folder** – optional, query parameter, string: path to the folder containing the document; omit to use the root folder.  \n- **storage** – optional, query parameter, string: name of the storage service to read the file from; if omitted the default storage is used.  \n- **loadEncoding** – optional, query parameter, string: character‑encoding name (e.g., “utf-8”, “windows-1252”) applied when loading an HTML or TXT document that does not specify its own encoding.  \n- **password** – optional, query parameter, string: password required to open an encrypted document.  \n- **includeComments** – optional, query parameter, boolean: set to true to include comments in the word count (default\u202ftrue); set to false to exclude them.  \n- **includeFootnotes** – optional, query parameter, boolean: set to true to include footnotes in the word count (default\u202ffalse); set to false to exclude them.  \n- **includeTextInShapes** – optional, query parameter, boolean: set to true to include text inside shapes in the word count (default\u202ffalse); set to false to exclude it.  \n\nThe tool returns a JSON object with the following properties, each an integer: **WordCount**, **PageCount**, **ParagraphCount**, **TableCount**, **ImageCount**, and **CharacterCount**.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name, "includeComments": include_comments, "includeFootnotes": include_footnotes, "includeTextInShapes": include_text_in_shapes}.items() if v is not None}
    url = f"/words/{filename}/statistics"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def words_replace_text(auth: AsposeAuthClient, filename: str, replace_request: dict[str, Any], folder_name: str | None = None, storage_name: str | None = None, load_encoding: str | None = None, destination_filename: str | None = None, revision_author: str | None = None, revision_date_time: str | None = None, dry_run: bool = False) -> PostReplaceTextResponse:
    'The tool replaces occurrences of specified text in a Word document stored in Aspose Cloud, optionally saving the result under a new name or location.  \n\nname (path, required): string – exact name of the source document.  \nreplaceText (body, required): object – must contain the keys:  \n\u202f\u202fOldValue (string) – text or regular‑expression pattern to be replaced.  \n\u202f\u202fNewValue (string) – text that will replace each match of OldValue.  \n\u202f\u202fIsMatchCase (boolean) – true for case‑sensitive matching, false otherwise.  \n\u202f\u202fIsMatchWholeWord (boolean) – true to match whole words only, false otherwise.  \n\u202f\u202fIsOldValueRegex (boolean) – true if OldValue is a regular expression, false otherwise.  \nfolder (query, optional): string – storage folder path that contains the source document.  \nstorage (query, optional): string – name of the Aspose Cloud storage to use.  \nloadEncoding (query, optional): string – character encoding (e.g., "utf-8") used when loading HTML or TXT files without an explicit encoding.  \npassword (query, optional): string – password for opening an encrypted document.  \ndestFileName (query, optional): string – name for the resulting document; if omitted the source document is overwritten.  \nrevisionAuthor (query, optional): string – initials of the author to attribute to any revisions created by this operation.  \nrevisionDateTime (query, optional): string – revision timestamp in ISO\u202f8601 format (e.g., "2023-04-01T13:45:00Z").  \n\nThe tool returns a JSON object conforming to the Aspose.Words Cloud DocumentResponse schema: it contains a “Document” object with the fields FileName (string) – name of the saved document; Path (string) – full storage path of the document; Storage (string) – storage name used; Size (integer) – file size in bytes; Href (string) – URL to download the document; and RequestId (string) – identifier of the request.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name, "loadEncoding": load_encoding, "destFileName": destination_filename, "revisionAuthor": revision_author, "revisionDateTime": revision_date_time}.items() if v is not None}
    url = f"/words/{filename}/replaceText"
    if dry_run:
        return {"dry_run": True, "operation": "PostReplaceText"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        json=replace_request,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def words_create_document(auth: AsposeAuthClient, storage_name: str | None = None, filename: str | None = None, folder_name: str | None = None, dry_run: bool = False) -> PutCreateDocumentResponse:
    'Creates a new document in Aspose Words cloud storage, using the supplied file name (including a supported extension) to determine the document format and placing it in the optional folder within the optional storage.  \n\n- **storage** – optional query parameter; type string; the name of the storage to use; if omitted the default storage is used.  \n- **fileName** – optional query parameter; type string; the name of the file to create; must include one of the supported extensions: `.doc`, `.docx`, `.docm`, `.dot`, `.dotm`, `.dotx`, `.flatopc`, `.fopc`, `.flatopc_macro`, `.fopc_macro`, `.flatopc_template`, `.fopc_template`, `.flatopc_template_macro`, `.fopc_template_macro`, `.wordml`, `.wml`, or `.rtf`.  \n- **folder** – optional query parameter; type string; the path to the folder within the chosen storage where the document will be created; if omitted the document is created at the storage root.  \n\nReturns a JSON object describing the created document, including its storage name, folder path, file name, and a URL for downloading the newly created file.'
    params = {k: v for k, v in {"storage": storage_name, "fileName": filename, "folder": folder_name}.items() if v is not None}
    url = "/words/create"
    if dry_run:
        return {"dry_run": True, "operation": "PutCreateDocument"}
    response = call_with_taxonomy(lambda: requests.put(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})
